
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POStock.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class KATEGORI
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KATEGORI()
    {

        this.URUN = new HashSet<URUN>();

    }


    public short KategoriID { get; set; }

    public string KategoriAd { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<short> KategoriUser { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<URUN> URUN { get; set; }

    public virtual USERS USERS { get; set; }

}

}
