
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace POStock.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class URUN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public URUN()
    {

        this.ALIS = new HashSet<ALIS>();

        this.SATIS = new HashSet<SATIS>();

    }


    public short UrunID { get; set; }

    public string UrunAd { get; set; }

    public Nullable<short> UrunKategori { get; set; }

    public Nullable<short> Stok { get; set; }

    public Nullable<bool> IsActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ALIS> ALIS { get; set; }

    public virtual KATEGORI KATEGORI { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SATIS> SATIS { get; set; }

}

}
